################################################################################
# Apache Guacamole Docker Compose Configuration
#
# Author: Adrian Johnson <adrian207@gmail.com>
# Version: 1.0
# Date: October 17, 2025
#
# Purpose: Deploy Apache Guacamole for web-based remote access
#
# Description:
#   This Docker Compose configuration deploys Apache Guacamole with PostgreSQL
#   backend on the bastion host. Provides web-based RDP/SSH/VNC access to all
#   servers in the datacenter through a single web interface.
#
# Services:
#   - guacamole-db: PostgreSQL 15 database
#   - guacd: Guacamole proxy daemon
#   - guacamole: Guacamole web application (port 8080)
#
# Usage:
#   docker-compose up -d
#
# Copyright (c) 2025 Adrian Johnson
# Licensed under MIT License
################################################################################

version: '3.8'

services:
  # Guacamole Database (PostgreSQL)
  guacamole-db:
    image: postgres:15-alpine
    container_name: guacamole-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${GUAC_DB_PASSWORD:-ChangeThisPassword123!}
    volumes:
      - guacamole-db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - guacamole-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guacamole_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Guacamole Daemon (guacd)
  guacd:
    image: guacamole/guacd:latest
    container_name: guacamole-daemon
    restart: unless-stopped
    networks:
      - guacamole-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 4822 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Guacamole Web Application
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      POSTGRES_HOSTNAME: guacamole-db
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${GUAC_DB_PASSWORD:-ChangeThisPassword123!}
      GUACAMOLE_HOME: /etc/guacamole
    depends_on:
      guacamole-db:
        condition: service_healthy
      guacd:
        condition: service_healthy
    networks:
      - guacamole-network
    volumes:
      - ./guacamole-config:/etc/guacamole
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/guacamole/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  guacamole-network:
    driver: bridge

volumes:
  guacamole-db-data:
    driver: local

